server.port=${PORT:8080}

# Customizable details for Chitkara API Qualifier
app.user.name=${APP_USER_NAME:sujal_arora}
app.user.dob=${APP_USER_DOB:17091999}
app.user.email=${APP_USER_EMAIL:sujal6067@gmail.com}
app.user.roll-number=${APP_USER_ROLL_NUMBER:2310991299}
